# Generated by Django 5.1.3 on 2024-12-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kelas',
            table='kelas',
        ),
    ]
