# Generated by Django 5.1.3 on 2024-12-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0003_vocabulary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='kelas',
        ),
        migrations.DeleteModel(
            name='Vocabulary',
        ),
        migrations.DeleteModel(
            name='kelas',
        ),
    ]
